### ISSUE TITLE
(To Do) Booze Suggestions to get Wasted

### ISSUE THREAD

**Issue by Vaygrim** [Vaygrim/wasted#1]
Taking suggestions for drinks we can add to the pack, to accompany the pack's name.
Things to keep in mind:

- No "R-Rated" drink names, let's keep it clean please
- Consider uniform prefixes / suffixes like "Mug of"... "Bottle of" ... etc. This will make everything easier for players to search for in NEI.
- If you are suggesting a drink, please consider accompanying your suggestion with a crafting recipe

**Comment by mallrat208** [comment]
As an addition to that, we may want to consider standardizing the 'size' of drinks.
Say for example we added Janx Spirit as a drink. It could come in Bottle form and Shot form
a 'Bottle of Janx Spirit' would have 4 uses. Or alternatively it could be crafted into 4 'Shot of Janx Spirit' for individually consumable items. If you had the 4 Shots you could then craft them back into a Bottle or to top off an Existing one.

**Comment by FoxBotGames** [comment]
Suggestions:
Shot of Sake ~ Wheat  Bottle-of-Water  Rice*   into Bottle of Sake
Shot of Ale ~ Wheat  Bottle-of-Water  Barley    into Mug of Ale
Shot of Wine ~ Grape  Bottle-of-Water  Grape   into Bottle of Wine
Wine Cooler(?) ~ Grape Bubbly-Water Sugar    Into ???
(*) meaning multiple options available

**Comment by Vaygrim** [comment]
This is now under the purview of "Bottom Shelf".
