### ISSUE TITLE
(CRASH) Using Bonemeal

### ISSUE THREAD

**Issue by Vaygrim** [Vaygrim/wasted#16]
v0.6.0 of the pack, I'm getting a crash whenever I use bonemeal.. on anything, I think. So far I've replicated three times:
- Once on a vanilla grass block
- Twice on a vanilla dirt block

In both cases when I come back , the grass I was trying to grow (so I could break it for seeds) was present. But breaking the grass then growing it back with bonemeal causes a fresh crash. Coming back from that, new grass to break.

[crash-2018-02-18_16.39.11-client.txt](https://github.com/Vaygrim/wasted/files/1735243/crash-2018-02-18_16.39.11-client.txt)

[crash-2018-02-18_16.41.34-client.txt](https://github.com/Vaygrim/wasted/files/1735242/crash-2018-02-18_16.41.34-client.txt)

**Comment by mallrat208** [comment]
That seems to be on Need to Breathe

**Comment by Vaygrim** [comment]
This has been corrected in the latest update.
