### ISSUE TITLE
(Request) Powered Thingies & Osmium

### ISSUE THREAD

**Issue by Vaygrim** [Vaygrim/wasted#17]
Only the "Kiln" from Powered Thingies (their powered furnace) seems to accept Osmium, is it possible that we could get their ore processing system to take it? (Powder Maker, etc)

**Comment by mallrat208** [comment]
Yeah, that mod had built in CraftTweaker support, shouldn't be hard

**Comment by Vaygrim** [comment]
Closing this. Would be nice to get it done but apparently feature implementation in Powered Thingies is .. bad.
