### ISSUE TITLE
HarvestCraft/Food Tweaks (Suggestion)

### ISSUE THREAD

**Issue by FoxBotGames** [Vaygrim/wasted#18]
According to Vaygrim the seed drops are somewhat 'underpar' from what might be needed. Perhaps a change in seed drops or more seed drops?

Food Nutrition Values are a little underwhelming, perhaps a 'tuning' to the configs of Hunger Overhaul?

**Comment by Vaygrim** [comment]
Already did one pass at the numbers in Hunger Overhaul. We'll have to test those and see if they're any goodl.

**Comment by Vaygrim** [comment]
We've updated HarvestCraft's seed drops from grass, and I've dialed back the saturation divider from Hunger Overhaul. Closing this until further notified that it's not sufficient.
