### ISSUE TITLE
(To Do) Vic's MW Weapons

### ISSUE THREAD

**Issue by Vaygrim** [Vaygrim/wasted#2]
Master List of Weapons to be kept from Vic's Modern Weapons

•    7.62x54mm
o          SV-98 (SR)
o          Mosin Magant M91/30 (BA-R)
o          Mosin Magant M91/30 PU (BA-R)
o          Dragunov SVD (SA-SR/DMR)
o          SVT-40 (SA-BR)
•    5.56x45mm NATO
o          Remington ACR (AR)
o          M416 (C)
o          M16A4 (AR)
o          AUG A3 (AR)
o          M249 SAW (LMG)
•    12 Gauge
o          Remington 870-Express (SH)
o          M1014 (SH)
o          Saiga-12 (SH)
•    7.62x51mm NATO
o          FN FAL (BR)
o          M14 DMR (DMR)
o          M21 (SR)
•    .45 ACP
o          USP .45 (P)
o          M1911 (P)
o          KRISS Vector (SMG)
•    9mm
o          Glock 18C (P)
o          P226 (P)
o          MP5 (SMG)
•    .50 BMG
o           Barrett M107 (AM-SR)
•    Mk153 SMAW

**Comment by XEridaniTribalX** [comment]
We're removing Vic's Modern Warfare and moving on to (most likely, but not certain) TechGuns 2, so I'm gonna close this up.
