### ISSUE TITLE
Cannot make TechGuns Laser Focus in TechGuns Reaction Chamber.

### ISSUE THREAD

**Issue by XEridaniTribalX** [Vaygrim/wasted#26]
I couldn't make the TG Laser Focus in the Reaction Chamber. I'm thinking it's having an issue with Tesla's Powered Thingies Liquid Redstone, which completely replaces TE's Destabilized Redstone. Every other recipe working the the RC though.

**Comment by FoxBotGames** [comment]
As of Version 1.0.3 Tesla's Powered Thingies is no longer replacing TE's Destabilized Redstone.
Can confirm crafting in SP working fine now, have yet to test on server.

**Comment by FoxBotGames** [comment]
Works on server I deem this issue magically solved (by mod updates?)
