### ISSUE TITLE
Creative Energy Cube (Mekanism) + The One Probe Client Crash

### ISSUE THREAD

**Issue by XEridaniTribalX** [Vaygrim/wasted#27]
It looks like TOP is not enjoying the Creative Energy Cube from Mek. Even placing one down is causing the client to crash, in both single player and on a server. Crash log included.
[crash-2018-03-21_21.19.49-client.txt](https://github.com/GrimCo/wasted/files/1836058/crash-2018-03-21_21.19.49-client.txt)

**Comment by Vaygrim** [comment]
Recheck this after I update the server to 1.0.0 tomorrow as it's got a TOP update that apparently fixes this issue. (It stems from a crash resulting from REALLY large RF numbers being displayed.)

**Comment by XEridaniTribalX** [comment]
Yep, problem is fixed in V1.0. Gonna close this issue up.
