### ISSUE TITLE
(Issue)(kinda...) TreeChopper assigning durability NBT tag to Chainsaw

### ISSUE THREAD

**Issue by TheDarkPreacher** [Vaygrim/wasted#28]
Tree chopper assigns a durability to the chainsaw on first use of 300, which means once it gets to 0 or below (Had one chainsaw get to -3 durability in testing) it stops interacting with TreeChopper, and instead just functions as a normal chainsaw, breaking one block at a time. There is no normal way to "repair" said chainsaw, and the chainsaw itself seems to simply ignore the durability tag assigned to it. Not sure if an anvil recipe is warranted, or if TC compat is needing to be pulled. Either way, issue has been reported to TC dev as of Mar 21 2018.

TC Ver. 1.12.2-1.2.4
TG2 Ver. 1.12.2-2.0.1.1

**Comment by FoxBotGames** [comment]
We removed the listing for the Chainsaw to be able to knock down a tree from the TreeChopper.cfg file.
I have no clue if we are going to see if there is a work around or live without it.

**Comment by Vaygrim** [comment]
Temporarily removed the chainsaw from the TreeChopper items whitelist until we can resolve the issue otherwise.
