### ISSUE TITLE
(To Do) Ore Tweaks

### ISSUE THREAD

**Issue by Vaygrim** [Vaygrim/wasted#3]
# **Ore Master List**
**Vanilla**
Iron, Gold, Lapis, Redstone, Diamond, Emerald

**Vic's Modern Warfare**
Silicon Ore (spawnsPerChunk="16")
Bauxite Ore (spawnsPerChunk="15")
Titanium Ore (spawnsPerChunk="14")
Sulfur Ore (spawnsPerChunk="13")
Copper Ore (spawnsPerChunk="0")
Lead Ore (spawnsPerChunk="0")
Tin Ore (spawnsPerChunk="0")
Tantalum Ore" spawnsPerChunk="9")
Ruby Ore (spawnsPerChunk="8")

**Thermal Expansion**
Copper, Tin, Silver, Lead, Nickel

**Mekanism**
Copper (PerChunk=16)
Osmium (PerChunk=12)
Salt (PerChunk=2)
Tin (PerChunk=14)

**Immersive Engineering**
Bauxite, Copper, Lead, Nickel, Silver, Uranium

**Comment by FoxBotGames** [comment]
We might be able to disable one of the Bauxite spawns as well, I do see it easier to disable Immersive Engineering's Bauxite ore as if we disable Vic's MW bauxite we will have to change 3 recipes as they dont have the "accepts all silver" setting. (Keep in mind Bauxite = Silver in either instance) Altho I have no idea if we can even disable Immersive ores. (Edit: I looked at the immersive configs, we can disable specific ores)

**Comment by mallrat208** [comment]
For the most part I recommend we flat-out disable the Vic's ores if possible and just alter the recipes of the items that use them. It adds way too many ores for what that mod actually does.

Biomes O Plenty also adds a suite of Gemstones to worldgen including Ruby.

Thermal Foundation gives us access to the following ores:
 - [x] Aluminum (Bauxite) 
 - [x] Copper
 - [ ] Iridium
 - [x] Lead
 - [ ] Mithril (Mana Infused)
 - [x] Nickel
 - [ ] Platinum
 - [x] Silver
 - [x] Tin

If we use them and only them as our primary sources we're only missing Osmium (which is actually close to Platinum), and Uranium. Salt is a block that generates in world like Clay but isn't required as it can be made in other ways.

I say we use the Thermal Foundation Ores where possible and just 'add-in' what we're missing from the other stuff. 

Going a bit further I'd also think we could reuse Platinum's texture to mask Mekanism Osmium so it matches worldgen bettter, and I could probably throw together a tinted Iridium that'll match Uranium.

**Comment by mallrat208** [comment]
Oh, as a related thing, we'll probably want to tell Immersive Engineering to favor giving out ThermalFoundation materials for the purposes of processing stuff

**Comment by Vaygrim** [comment]
Regarding turning off all Vic's Ores, I'm fine with this would mean not only tweaking 'off' all the unused ammo.. unused accessories.. and unused weapons, PLUS remapping all the recipes for everything we keep.

**Comment by mallrat208** [comment]
There's not a lot that would need to be changed for removing the Ores.

The things unique to Vic's are 
- Silicon
   - Exclusively used to craft Diodes and Transistors. easily replaced
- Titanium
   - Marine and Spetsnaz Armors as well as Optic Glass, Again, easily replaced
- Sulfur
   - Used to craft gunpowder, not required
- Tantalum
   - Used to craft Capacitor, again, easily replaced

**Comment by mallrat208** [comment]
Oh, we're also going to have issues with Prismarine and potentially Quartz. We can keep the machine recipes we add from R&D but a Prismarine Ore wouldn't be too hard to do if we want go that route instead.

**Comment by Vaygrim** [comment]
Tantalum is basically Osmium.
Mekanism adds Sulfur (craftable, I believe)

Also we're going to (as soon as I figure out how) have Hell biomes in the overworld (periodically) so we could always generate Nether Quartz in those biomes via COFH Core.

**Comment by FoxBotGames** [comment]
Looking through there are 10 to 13 (more or less due to semi-skimming and optional items that we may not use) recipes that have to be changed due to Vic's MW mod not having an "any of this type" setting on some of its recipes. 

Sulfur is 'craftable' by mekanism meaning that it has a chance as a second output for certain items in a machine. (like 10 - 30% chance default?)

**Comment by Vaygrim** [comment]
In accordance with our existing Ore-Gen concerns, we're going to need pockets of obsidian to generate down low near bedrock .. as water is going to be far more scarce. (Unless we want to generate pools of water down that low as well?).

**Comment by XEridaniTribalX** [comment]
Since we're dropping Vic's MW, and most likely going with TechGuns 2, some of this will get simplified. TG2 has Copper, Tin, Lead, Titanium and Uranium as world-gen, and uses Bronze and Steel. From what I've seen, everything is OreDicted, so it can use options from other mods, so we won't need to change any of their recipes. 

I already disabled Copper, Tin, Lead and Uranium generation in the TG2 configs since we have TE and IE for those ores, but left Titanium on, since no other mods we have actually generate it. Titanium is used in a fair amount of the late-game mod, so I wouldn't recommend disabling it.

**Comment by Vaygrim** [comment]
At present I'm count this as done. We haven't had to enable / disable anything in a while, and we've got ore gen divided up between inside and outside domes (and it works now, swear).
