### ISSUE TITLE
Mod Suggestion: UniDict

### ISSUE THREAD

**Issue by ChromeMystic** [Vaygrim/wasted#42]
This Mod helps with unifying different Ores from different Mods.

[Curse Link](https://minecraft.curseforge.com/projects/unidict)

**Comment by Vaygrim** [comment]
While I am sure UniDict is a very useful and powerful tool when it comes to modpack creation, we here at GrimCo have had several bad experiences with it in the past. It can come across far too strong in its efforts, and cause more issues than it resolves.

Thanks for the suggestion tho, we do appreciate it!
