### ISSUE TITLE
Mod Suggestion: Thut's Elevators

### ISSUE THREAD

**Issue by ChromeMystic** [Vaygrim/wasted#43]
The Smoothest Elevators out there, even though they are a bit more Complicated to Config :)

[Curse Link](https://minecraft.curseforge.com/projects/thuts-elevators?gameCategorySlug=mc-mods&projectID=224375)

**Comment by FoxBotGames** [comment]
We have plenty of elevators. One(s) from _Elevator Mod_ and the RF_Tools Elevator. Both popular and doesn't need a ton of work done on them.

**Comment by ChromeMystic** [comment]
I know, i currently use the Elevators from elevators mod, but I really like those I mentioned. And I still wanted to post them if only for you guys to know about them in a future Modpack :D

**Comment by mallrat208** [comment]
While a great mod, this is one that will probably never be included. We've had a few.... over eager people incessantly bring this mod to the point it's associated to much with annoyance
