### ISSUE TITLE
broken Purple Plastic recipe

### ISSUE THREAD

**Issue by SOTMead** [Vaygrim/wasted#46]
It apparently is a component for an Artificial Shulker Shell. I wasn't trying to make it, just stumbled across it. 
![image](https://user-images.githubusercontent.com/29783622/38447939-b267ef90-39ce-11e8-9eff-b0501f15af98.png)

**Comment by mallrat208** [comment]
I thought we had straightened that out, I'll check to make sure nothing got reverted when I get home

**Comment by FoxBotGames** [comment]
Might have been reverted in my wall that was a fail?

**Comment by FoxBotGames** [comment]
Seems all 3 items added in by the scripts are messed up, icon and name, recipes still function.
