### ISSUE TITLE
Mod Suggestions: Scannable and CarryOn

### ISSUE THREAD

**Issue by jengeld4** [Vaygrim/wasted#52]
As the name suggest. Both are more quality of life than anything else.

Scannable adds a fortresscraft evolved-like scanner that is modifiable and color codes ores. Might need some configuration changes to include modded ores properly though. Mainly to help with mining pre-digital miner.

CarryOn basically allows the player to pick up certain entities (chest, machines, passive mobs) and move them with out breaking them. Slows player while doing so (config setting, I think). Nice alternative to a chest mover.

**Comment by FoxBotGames** [comment]
We will investigate both of these mods, thanks for the suggestions!
