### ISSUE TITLE
Void Ore Miner[Environmental Tech] not producing Titanium Ore[techguns]

### ISSUE THREAD

**Issue by williamoverstreet** [Vaygrim/wasted#58]
SMP MC, Wasted 1.0.7

The miners do produce uranium, just no titanum.

**Comment by Dragonracer73** [comment]
what tier miner are you using? I know for sure some ET items are tier based

**Comment by williamoverstreet** [comment]
I've used 1-4. JEI also shows no production from for titanium, unlike uranium which can be made from miners 1-6.

**Comment by FoxBotGames** [comment]
Issue fixed in next update
