### ISSUE TITLE
(To Do) Mob Spawns

### ISSUE THREAD

**Issue by Vaygrim** [Vaygrim/wasted#6]
Need to specify what spawns where, and how (In Control & Lost Souls).
Make sure we're only spawning Vic's MW Hostiles with the weapons on our "MW Guns Whitelist". We don't want hostiles spawning with ammo or weapons unusable / uncraftable by the players.

**Comment by mallrat208** [comment]
I would recommend effectively disabling the spawns of Vic's Mobs in it's config (setting their chance to 0) and instead using InControl to adding them so that we can explicitly control how and where they spawn since they currently don't follow normal hostile mob spawn rules

**Comment by Vaygrim** [comment]
Can we control what weapons they're spawning with, if we spawn them using In Control?

**Comment by mallrat208** [comment]
We can actually

**Comment by TheDarkPreacher** [comment]
Air Support has a config that disables all vanilla mob spawns (passive, hostile, ambient, and water mobs). This config is default set to disable spawns, needs to be set to true to get any spawns. Add to next version?

**Comment by XEridaniTribalX** [comment]
On the topic of mob spawns, we'll need to do this with whatever TechGuns 2 mobs we decide to go with.

**Comment by FoxBotGames** [comment]
When Techguns Mobs' Weighted Spawn is at 0 a server crash will happen, from the looks it was trying to spawn something and only pulling 0s. Can be 'fixed' with inControl by letting it do its thing then telling it no. (Or as MallRat describes it "Slapping it back in place")

**Comment by Vaygrim** [comment]
**Desired mob spawn setups:**
- IN BIOSPHERES: Vanilla standard overworld mobs only, no modded critters.
- OUTSIDE BIOSPHERES: Everything (Vanilla, TechGuns, Lost Souls, Thermal Suite, etc)

**For outside spawning:**
- TG Human & Zombie Bandits in Lost Cities (exclusively?)
- Haunted Buildings should have their Lost Souls spawns in addition to TechGuns mobs
- Nether biomes add Zombie Pigmen, Magma Cubes, and Ghasts to normal spawns (Blazes underground only?)
- Ominous Woods add Wither Skeletons and Cave Spiders (the tiny poisonous ones, yes) to normal spawns
- TechGuns' more radical mobs should spawn in any non-sphere biome, below Y-level 60

Think this will work? Currently I don't know how slimes will work, that's still up in the air.

**Comment by Vaygrim** [comment]
Mob Spawns appear to be up and running appropriately, closing this and counting as 'done'.
