### ISSUE TITLE
Crash with Cooking for Blockheads

### ISSUE THREAD

**Issue by mallrat208** [Vaygrim/wasted#63]
Wasted version 1.1.3

Crash Report: https://gist.github.com/mallrat208/d65cf3acae6ee514f1c4638ffb40b978

It looks like this is fixed by updating Cooking For Blockheads as the very next release mentions a crash with the recipe book. Should probably be included in the final Wasted update

**Comment by XEridaniTribalX** [comment]
Very old issue, closing.
