### ISSUE TITLE
Bagging quest (Chisels & Bits) can't be completed

### ISSUE THREAD

**Issue by xenoflot** [Vaygrim/wasted#64]
Single player, ver 1.1.4-Twitch
Completed the Iron Chisel quest.
Crafted a bit bag but it's not being recognised, even when clicking Detect.
Spawned one in, same.
Filled a bag with stone bits, same.

**Comment by FoxBotGames** [comment]
It was a poor choice of me to choose to use the Bit Bags as their ID's are all sorts of funky for quests.
If you have cheat mode enabled for your save use the command `/bq_admin edit` and force the quest through.

If we do updates for our various packs sometime soon I will remove the bag as a requirement for those types of quests.

An alternative (so long as you have cheat mode enabled as well) is `bq_admin complete 69 [username]`
(69 being the quest number I know it is and [username] being your in game name)

**Comment by xenoflot** [comment]
Thanks for the snappy response!

**Comment by xenoflot** [comment]
I ran the second command and got the next one (Editing) to unlock, but Bagging itself remained incomplete and so Editing didn't have its pre-req. 68 perhaps? :D

I've sorted myself out by editing the Bagging quest so all's well. Cheers!
