### ISSUE TITLE
(To Do) HarvestCraft

### ISSUE THREAD

**Issue by Vaygrim** [Vaygrim/wasted#7]
HarvestCraft needs to be configured. Dial back garden generation rates, double check they have spread limits, etc. We also need to pick what currency we're going to use for the HC Market (are we gonna use their goofy "Garlicoin" ?)

**Comment by FoxBotGames** [comment]
Current Config for Harvestcraft gardens: (Defalt?)
SpeedRate ~ 30 (30% chance to spawn per tick)
dropAmount ~ 3 (minimum/median of items dropped when breaking a Garden)
spreadMax ~ 8
We can also make seeds drop from breaking grass, this may be an alternative to food issue?

**Comment by mallrat208** [comment]
Are the spheres single biome when they are setup or can multiple biomes span a single sphere?

The idea of venturing into another bio sphere in search of new food stores sounds kind of neat

**Comment by Vaygrim** [comment]
Currently Spheres can be mixed biomes. I'm not sure how to limit it to one biome per sphere, we'd have to check for advice from McJty on that.

**Comment by FoxBotGames** [comment]
Pam's Harvestcraft Loot Tables are bugged, regular chance to get inside a loot table for any loot chest, but once the Harvestcraft food is inside the LootChests' Loot Table the chest gets FILLED with Harvestcraft food.
Report sent to Pam's Harvestcraft GitHub and as of this post no response.

Starting food is still an issue, we can either turn on seed drops from grass or give more food as quests. Keep in mind many people will probably not use the quests.

**Comment by Vaygrim** [comment]
I'm actually not opposed to turning on seed drops from grass for say... 6 to 12 things? Find say 12 food items that can be used in low end / starter recipes for food (nothing that's ONLY used in elaborate multi-step high end stuff) and turn on the seed drops for those. Totally do-able.

**Comment by Vaygrim** [comment]
Closing as 'done'.
