### ISSUE TITLE
(TO DO) Simple Recipes to add

### ISSUE THREAD

**Issue by Vaygrim** [Vaygrim/wasted#9]
List of recipes to add for simple 'quality of life' stuff:

2 Logs -> 16 Sticks (Use OREDICT)
8 Logs in a circle -> 4 Wooden Chests (OREDICT, Vanilla Chests)
4 String + Slime Ball -> Spider Web

**Comment by Vaygrim** [comment]
A lot of these we might be able to just copy over from "GrimCo R&D"

**Comment by mallrat208** [comment]
Do we want to copy over the CT recipes I made for upgrading TE Machines via crafting instead of using kits?

**Comment by Vaygrim** [comment]
> Do we want to copy over the CT recipes I made for upgrading TE Machines via crafting instead of using kits?

Yes, I think that might be a real good idea. There's a lot of custom recipe "quality of life" stuff we did in R&D that I'd like to carry over to here.

**Comment by Vaygrim** [comment]
All done, closing this.
